create table app_users (
    id bigint generated by default as identity primary key,
    username varchar(255) not null unique,
    password_hash varchar(255) not null,
    display_name varchar(120) not null,
    role varchar(40) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(120) not null,
    updated_by varchar(120) not null
);

create table customers (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    email varchar(255) not null,
    phone varchar(40) not null,
    tax_id varchar(8) not null,
    industry varchar(120) not null,
    owner_name varchar(120) not null,
    status varchar(40) not null,
    contract_start_date date,
    contract_end_date date,
    renewal_due_date date,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(120) not null,
    updated_by varchar(120) not null
);

create table contacts (
    id bigint generated by default as identity primary key,
    customer_id bigint not null references customers(id),
    name varchar(120) not null,
    title varchar(120) not null,
    email varchar(255) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(120) not null,
    updated_by varchar(120) not null
);

create table interactions (
    id bigint generated by default as identity primary key,
    customer_id bigint not null references customers(id),
    type varchar(40) not null,
    occurred_at timestamp not null,
    content varchar(2000) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(120) not null,
    updated_by varchar(120) not null
);

create table opportunities (
    id bigint generated by default as identity primary key,
    customer_id bigint not null references customers(id),
    name varchar(255) not null,
    stage varchar(40) not null,
    amount numeric(14, 2) not null,
    expected_close_date date,
    type varchar(40) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(120) not null,
    updated_by varchar(120) not null
);

create table knowledge_documents (
    id bigint generated by default as identity primary key,
    doc_type varchar(80) not null,
    title varchar(255) not null,
    content varchar(4000) not null,
    similarity_hint numeric(5, 2) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(120) not null,
    updated_by varchar(120) not null
);

create index idx_customers_owner on customers(owner_name);
create index idx_interactions_customer_time on interactions(customer_id, occurred_at);
create index idx_opportunities_customer_stage on opportunities(customer_id, stage);
create index idx_knowledge_doc_type on knowledge_documents(doc_type);

