-- V22：正式 CRM 任務與活動；外鍵刻意不使用 ON DELETE CASCADE，保留歷史任務並阻止誤刪主資料。
CREATE TABLE crm_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customers(id),
    opportunity_id BIGINT REFERENCES opportunities(id),
    contact_id BIGINT REFERENCES contacts(id),
    task_type VARCHAR(32) NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'OPEN',
    priority VARCHAR(16) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(4000),
    assignee_id BIGINT NOT NULL REFERENCES app_users(id),
    scheduled_start TIMESTAMP NOT NULL,
    scheduled_end TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    postpone_count INTEGER NOT NULL DEFAULT 0,
    source VARCHAR(32) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by VARCHAR(120) NOT NULL,
    updated_by VARCHAR(120) NOT NULL,
    CONSTRAINT chk_crm_tasks_type CHECK (task_type IN ('PHONE_CALL','EMAIL','MEETING','GENERAL')),
    CONSTRAINT chk_crm_tasks_status CHECK (status IN ('OPEN','IN_PROGRESS','COMPLETED','CANCELLED')),
    CONSTRAINT chk_crm_tasks_priority CHECK (priority IN ('LOW','NORMAL','HIGH','URGENT')),
    CONSTRAINT chk_crm_tasks_source CHECK (source IN ('MANUAL','BUSINESS_CARD','MEETING_AI','FOLLOW_UP_AI')),
    CONSTRAINT chk_crm_tasks_schedule CHECK (scheduled_end > scheduled_start),
    CONSTRAINT chk_crm_tasks_postpone_count CHECK (postpone_count >= 0),
    CONSTRAINT chk_crm_tasks_completed_at CHECK (status <> 'COMPLETED' OR completed_at IS NOT NULL)
);

CREATE INDEX idx_crm_tasks_scheduled_start ON crm_tasks(scheduled_start);
CREATE INDEX idx_crm_tasks_assignee_status_start ON crm_tasks(assignee_id, status, scheduled_start);
CREATE INDEX idx_crm_tasks_customer ON crm_tasks(customer_id);
CREATE INDEX idx_crm_tasks_opportunity ON crm_tasks(opportunity_id);
CREATE INDEX idx_crm_tasks_contact ON crm_tasks(contact_id);
