-- AI 治理：記錄每次 LLM 呼叫的用量與答案，以及採納/拒絕回饋
-- 注意：本兩表為治理稽核用途，採簡化稽核欄位（自行管理 created_at），不繼承 AuditableEntity 四欄位
create table ai_call_log (
    id bigint generated by default as identity primary key,
    customer_id bigint,
    call_type varchar(40) not null,
    model varchar(120),
    prompt_tokens int not null default 0,
    completion_tokens int not null default 0,
    total_tokens int not null default 0,
    ai_enabled boolean not null,
    pii_masked boolean not null,
    answer text,
    created_at timestamp with time zone not null
);
create index idx_ai_call_log_customer on ai_call_log(customer_id);
create index idx_ai_call_log_created on ai_call_log(created_at);

create table ai_feedback (
    id bigint generated by default as identity primary key,
    call_log_id bigint not null references ai_call_log(id),
    decision varchar(20) not null,
    note varchar(1000),
    created_at timestamp with time zone not null,
    created_by varchar(120) not null
);
create index idx_ai_feedback_call on ai_feedback(call_log_id);
