-- 對話記憶：落庫每輪 user/assistant 訊息，含 1024 維 embedding 供語意檢索
-- 注意：採簡化稽核欄位（自行管理 created_at），不繼承 AuditableEntity 四欄位；embedding 不映進 JPA 實體（用 JdbcTemplate）
create table chat_messages (
    id bigint generated by default as identity primary key,
    customer_id bigint not null references customers(id),
    role varchar(20) not null,
    content text not null,
    embedding vector(1024),
    created_at timestamp with time zone not null
);
-- 時序查詢索引：依客戶取最近 N 則
create index idx_chat_messages_customer_created on chat_messages(customer_id, created_at);
-- 語意檢索索引：HNSW cosine 近鄰
create index idx_chat_messages_embedding on chat_messages using hnsw (embedding vector_cosine_ops);
