-- SP6 情緒意圖雷達：每則互動的情緒(sentiment)+分數+意圖(intent)分析結果落庫
-- 注意：採簡化稽核欄位，自行管理 analyzed_at（與 InteractionInsight entity 一致），不繼承 AuditableEntity 四欄位
create table interaction_insights (
    id bigint generated by default as identity primary key,
    interaction_id bigint not null unique references interactions(id),
    customer_id bigint not null,
    sentiment varchar(20) not null,
    sentiment_score int not null,
    intent varchar(40) not null,
    analyzed_at timestamp with time zone not null
);
create index idx_interaction_insights_customer on interaction_insights(customer_id);
create index idx_interaction_insights_intent on interaction_insights(intent);
create index idx_interaction_insights_analyzed on interaction_insights(analyzed_at);
