-- SP7：泛用個人偏好表（本次用於 dashboard_layout，未來可擴充其他偏好）
create table user_preferences (
    id bigint generated by default as identity primary key,
    user_id bigint not null references app_users(id),
    pref_key varchar(64) not null,
    pref_value text not null,
    updated_at timestamp with time zone not null,
    constraint uq_user_pref unique (user_id, pref_key)
);
create index idx_user_pref_user on user_preferences(user_id);
